services:
  mariadb:
    extends:
      file: ../../services/mariadb/docker-compose.yml
      service: mariadb
  photoprism:
    extends:
      file: ../../services/photoprism/docker-compose.yml
      service: photoprism
    ports:
      - 2342:2342
    depends_on:
      - mariadb
  mediamtx:
    privileged: true
    extends:
      file: ../../services/mediamtx/docker-compose.yml
      service: mediamtx
    network_mode: host
  staticwebserver:
    extends:
      file: ../../services/staticwebserver/docker-compose.yml
      service: staticwebserver
    ports:
      - 8787:80