services:
  lldap:
    image: lldap/lldap:latest
    container_name: lldap
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/lldap/data:/data
    extends:
      file: ../../commons/compose.yml
      service: base
