services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/authelia/config:/config
      - ${HONEYPI_HOME}/authelia/secrets:/secrets
    extends:
      file: ../../commons/compose.yml
      service: base
