services:
  wireguard:
    image: linuxserver/wireguard:${HONEYPI_APP_VERSION:-latest}
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ${HONEYPI_HOME}/wireguard/config:/config
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:${HONEYPI_APP_VERSION:-latest}
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${HONEYPI_HOME}/wireguard/ui/db:/app/db
      - ${HONEYPI_HOME}/wireguard/ui/config:/etc/wireguard
    env_file:
      - ./service.env