#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

POSITIONAL_ARGS=()

MODULES=$(ls $SCRIPT_DIR/modules | xargs -n 1 basename)
SERVICE_MODULES=$(ls $SCRIPT_DIR/services | xargs -n 1 basename)
STACK_MODULES=$(ls $SCRIPT_DIR/stacks | xargs -n 1 basename)
# HONEYPI_COMPOSE_FILE=$PWD/docker-compose.yml

loadEnv() {
  source $1
  source $SCRIPT_DIR/commons/commons.env
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      echo "
honeypi

Usage:
  honeypi stack <name>
  honeypi service <name>
  honeypi module <name>
  honeypi env <env>
  honeypi -h | --help
Options:
  -h --help                  Show this screen.
  -e --environment=<env>     Environment [default: local].
  -f --file=<path>           Path to docker-compose.yml.
"
      shift # past argument
      exit 0
      ;;
    -e|--environment)
      HONEYPI_ENVIRONMENT="$2"
      shift # past argument
      shift # past value
      ;;
    -f|--file)
      HONEYPI_COMPOSE_FILE="$2"
      shift # past argument
      shift # past value
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [ "$1" = "env" ]; then
  shift
  echo "Loading environment from '${HONEYPI_ENVIRONMENT}'.env"
  [ -f "$PWD/$HONEYPI_ENVIRONMENT.env" ] && loadEnv "$PWD/$HONEYPI_ENVIRONMENT.env"
  set | grep HONEYPI_
  exit 0
elif [ "$1" = "module" ]; then
  shift
  [ -f "$PWD/$HONEYPI_ENVIRONMENT.env" ] && loadEnv "$PWD/$HONEYPI_ENVIRONMENT.env"
  echo "Module: '$1'"
  . $SCRIPT_DIR/modules/$1/install.sh
  exit 0
elif [ "$1" = "service" ]; then
  shift
  [ -f "$PWD/$HONEYPI_ENVIRONMENT.env" ] && loadEnv "$PWD/$HONEYPI_ENVIRONMENT.env"
  echo "Service: '$1'"
  COMPOSE_FILE="$COMPOSE_FILE -f $SCRIPT_DIR/services/$1/docker-compose.yml"
  [ -f "$HONEYPI_COMPOSE_FILE" ] && COMPOSE_FILE="$COMPOSE_FILE -f $HONEYPI_COMPOSE_FILE"
  shift
  ACTION="up -d"
  [ ! -z "${*}" ] && ACTION="${*}"
  docker compose $COMPOSE_FILE --env-file $PWD/$HONEYPI_ENVIRONMENT.env $ACTION
  exit 0
elif [ "$1" = "stack" ]; then
  shift
  [ -f "$PWD/$HONEYPI_ENVIRONMENT.env" ] && loadEnv "$PWD/$HONEYPI_ENVIRONMENT.env"
  echo "Stack: '$1'"
  COMPOSE_FILE="$COMPOSE_FILE -f $SCRIPT_DIR/stacks/$1/docker-compose.yml"
  [ -f "$HONEYPI_COMPOSE_FILE" ] && COMPOSE_FILE="$COMPOSE_FILE -f $HONEYPI_COMPOSE_FILE"
  shift
  ACTION="up -d"
  [ ! -z "${*}" ] && ACTION="${*}"
  docker compose $COMPOSE_FILE --env-file $PWD/$HONEYPI_ENVIRONMENT.env $ACTION
  exit 0
else
  echo "No argument(s) provided. Run -h for help."
  exit 0
fi

