#!/bin/bash

POSITIONAL_ARGS=()

MODULES=$(ls modules | xargs -n 1 basename -s .sh)
SERVICE_MODULES=$(ls services | xargs -n 1 basename)
STACK_MODULES=$(ls stacks | xargs -n 1 basename)

loadEnv() {
  source $1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      echo 'honeypi'
      echo
      echo 'Usage:'
      echo '  honeypi stack <name>'
      echo '  honeypi service <name>'
      echo '  honeypi module <name>'
      echo '  honeypi sync <from> <to>'
      echo '  honeypi env <env>'
      echo '  honeypi connect <name>'
      echo '  honeypi -h | --help'
      echo 'Options:'
      echo '  -h --help                  Show this screen.'
      echo '  -e --environment=<env>     Environment [default: local].'
      shift # past argument
      exit 0
      ;;
    -e|--environment)
      HONEYPI_ENVIRONMENT="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [ "$1" = "env" ]; then
  shift
  echo "Loading environment from '${HONEYPI_ENVIRONMENT}'.env"
  [ -f "$HONEYPI_ENVIRONMENT.env" ] && loadEnv "$HONEYPI_ENVIRONMENT.env"
  set | grep HONEYPI_
  exit 0
elif [ "$1" = "sync" ]; then
  shift
  [ -f "$HONEYPI_ENVIRONMENT.env" ] && loadEnv "$HONEYPI_ENVIRONMENT.env"
  [[ ! "$1" = "" ]] && URL=$1 || URL=${HONEYPI_HOST_URL:-local}
  DIR="$(dirname "$(readlink -f "$0")")"
  DIR=${2:-"$DIR"}
  echo "Syncing to '${URL}' from '${DIR}'"
  rsync -chavzP --stats -e "ssh -A" $DIR/* $URL/
  exit 0
elif [ "$1" = "connect" ]; then
  shift
  [ -f $HONEYPI_ENVIRONMENT.env ] && loadEnv $HONEYPI_ENVIRONMENT.env
  echo "Connecting to '$1'"
  docker exec -it $1 /bin/bash
  exit 0
elif [ "$1" = "service" ]; then
  shift
  [ -f $HONEYPI_ENVIRONMENT.env ] && loadEnv $HONEYPI_ENVIRONMENT.env
  echo "Deploying services: '${@}'"
  for arg in "${@}"
  do
    docker compose -f "./apps/$arg/docker-compose.yml" --env-file $HONEYPI_ENVIRONMENT.env up -d
  done
  exit 0
elif [ "$1" = "module" ]; then
  shift
  [ -f $HONEYPI_ENVIRONMENT.env ] && loadEnv $HONEYPI_ENVIRONMENT.env
  echo "Deploying modules: '${@}'"
  for arg in "${@}"
  do
    . ./modules/$arg.sh
  done
  exit 0
elif [ "$1" = "stack" ]; then
  shift
  [ -f $HONEYPI_ENVIRONMENT.env ] && loadEnv $HONEYPI_ENVIRONMENT.env
  echo "Deploying stacks: '${@}'"
  for arg in "${@}"
  do
    export UID
    COMPOSE_FILE="./stacks/$arg/docker-compose.yml"
    docker compose -f $COMPOSE_FILE --env-file $HONEYPI_ENVIRONMENT.env up -d
  done
else
  echo "No argument(s) provided. Run -h for help."
  exit 0
fi

