services:
  matomo:
    image: matomo:latest
    container_name: matomo
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/matomo/html:/var/www/html:z
    extends:
      file: ../../commons/compose.yml
      service: base
