version: "3.5"

services:
  server:
    build:
        context: .
        dockerfile: Dockerfile
        target: production
    image: pm2/pm2:${HONEYPI_APP_VERSION:-latest}
    restart: unless-stopped
    working_dir: /app
    container_name: "pm2"
    volumes:
      - ${HONEYPI_HOME}/pm2/app:/app
    command: "yarn run start:prod"
    extends:
      file: ../../commons/compose.yml
      service: base