services:
  memcached:
    image: memcached:${HONEYPI_APP_VERSION:-latest}
    container_name: memcached
    command: memcached -m 15
    restart: unless-stopped
    extends:
      file: ../../commons/compose.yml
      service: base