services:
  soketi:
    image: quay.io/soketi/soketi:${HONEYPI_SOKETI_VERSION:-latest}
    restart: unless-stopped
    container_name: soketi
    volumes:
      - ${HONEYPI_CONFIG}/soketi/soketi.json:/app/config/soketi.json
    command:
      - "node"
      - "/app/dist/server.js"
      - "--config"
      - "/app/config/soketi.json"
