services:
  webdav:
    image: ugeek/webdav:arm
    container_name: webdav
    restart: always
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env
