services:  
  mediamtx:
    privileged: true
    extends:
      file: ../../services/mediamtx/docker-compose.yml
      service: mediamtx
    devices:
     - /dev/video0:/dev/video0
    volumes:
      - ${HONEYPI_CONFIG}/mediamtx/config/mediamtx.yml:/mediamtx.yml
    network_mode: host