services:
  hydra:
    image: oryd/hydra:latest
    restart: unless-stopped
    container_name: hydra
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - ${HONEYPI_HYDRA_CONFIG}:/etc/config/hydra
    extends:
      file: ../../commons/compose.yml
      service: base
  hydra-migrate:
    image: oryd/hydra:latest
    container_name: hydra-migrate
    restart: on-failure
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - ${HONEYPI_HOME}/hydra/config:/etc/config/hydra
    extends:
      file: ../../commons/compose.yml
      service: base
  hydra-consent:
    image: ${HONEYPI_DOCKER_REGISTRY}/hydra-login-consent-node
    container_name: hydra-consent
    restart: unless-stopped
    build: .
    extends:
      file: ../../commons/compose.yml
      service: base