services:
  mariadb:
    extends:
      file: ../../services/mariadb/docker-compose.yml
      service: mariadb
  postgres:
    extends:
      file: ../../services/postgres/docker-compose.yml
      service: postgres
  redis:
    extends:
      file: ../../services/redis/docker-compose.yml
      service: redis
  elasticsearch:
    extends:
      file: ../../services/elasticsearch/docker-compose.yml
      service: elasticsearch
  gitea:
    extends:
      file: ../../services/gitea/docker-compose.yml
      service: gitea
    ports:
      - 7000:3000
      - 2222:22
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`${HONEYPI_GITEA_HOST}`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=resolver
      - traefik.http.routers.gitea.service=gitea
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
      - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=2222
  woodpecker-server:
    extends:
      file: ../../services/woodpecker/docker-compose.yml
      service: woodpecker-server
    ports:
      - 8000:8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.woodpecker.rule=Host(`${HONEYPI_WOODPECKER_HOST}`)
      - traefik.http.routers.woodpecker.entrypoints=websecure
      - traefik.http.routers.woodpecker.tls.certresolver=resolver
      - traefik.http.routers.woodpecker.service=woodpecker
      - traefik.http.services.woodpecker.loadbalancer.server.port=8000
  woodpecker-agent:
    extends:
      file: ../../services/woodpecker/docker-compose.yml
      service: woodpecker-agent
  mastodon:
    extends:
      file: ../../services/mastodon/docker-compose.yml
      service: mastodon
    ports:
      - 3000:3000
    depends_on:
      - mastodon-init
    labels:
      - traefik.enable=true
      - traefik.http.routers.mastodon.rule=Host(`${HONEYPI_MASTODON_HOST}`)
      - traefik.http.routers.mastodon.entrypoints=websecure
      - traefik.http.routers.mastodon.tls.certresolver=resolver
      - traefik.http.routers.mastodon.service=mastodon
      - traefik.http.services.mastodon.loadbalancer.server.port=3000
  mastodon-init:
    extends:
      file: ../../services/mastodon/docker-compose.yml
      service: mastodon-init
    depends_on:
      - redis
      - postgres
  mastodon-streaming:
    extends:
      file: ../../services/mastodon/docker-compose.yml
      service: mastodon-streaming
    depends_on:
      - redis
      - postgres
  mastodon-sidekiq:
    extends:
      file: ../../services/mastodon/docker-compose.yml
      service: mastodon-sidekiq
    depends_on:
      - redis
      - postgres
  homeassistant:
    extends:
      file: ../../services/homeassistant/docker-compose.yml
      service: homeassistant
    ports:
      - 8123:8123
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`${HONEYPI_HOMEASSISTANT_HOST}`)
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.routers.homeassistant.tls.certresolver=resolver
      - traefik.http.routers.homeassistant.service=homeassistant
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
      - traefik.http.middlewares.authentik.forwardauth.address=http://authentik:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      - traefik.http.routers.homeassistant.middlewares=authentik@docker
  photoprism:
    extends:
      file: ../../services/photoprism/docker-compose.yml
      service: photoprism
    ports:
      - 2342:2342
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true
      - traefik.http.routers.photoprism.rule=Host(`${HONEYPI_PHOTOPRISM_HOST}`)
      - traefik.http.routers.photoprism.entrypoints=websecure
      - traefik.http.routers.photoprism.tls.certresolver=resolver
      - traefik.http.routers.photoprism.service=photoprism
      - traefik.http.services.photoprism.loadbalancer.server.port=2342
  n8n:
    extends:
      file: ../../services/n8n/docker-compose.yml
      service: n8n
    ports:
      - 5678:5678
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${HONEYPI_N8N_HOST}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=resolver
      - traefik.http.routers.n8n.service=n8n
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.middlewares.authentik.forwardauth.address=http://authentik:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      - traefik.http.routers.n8n.middlewares=authentik@docker
  authentik-worker:
    extends:
      file: ../../services/authentik/docker-compose.yml
      service: authentik-worker
    depends_on:
      - authentik
  authentik:
    extends:
      file: ../../services/authentik/docker-compose.yml
      service: authentik
    ports:
      - 9000:9000
      - 9443:9443
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik.rule=Host(`${HONEYPI_AUTHENTIK_HOST}`) || ((Host(`${HONEYPI_N8N_HOST}`) || Host(`${HONEYPI_HOMEASSISTANT_HOST}`)) && PathPrefix(`/outpost.goauthentik.io/`))
      - traefik.http.routers.authentik.entrypoints=websecure
      - traefik.http.routers.authentik.tls.certresolver=resolver
      - traefik.http.routers.authentik.service=authentik
      - traefik.http.services.authentik.loadbalancer.server.port=9000
    depends_on:
      - redis
      - postgres
  traefik:
    extends:
      file: ../../services/traefik/docker-compose.yml
      service: traefik
    ports:
      - 80:80
      - 8080:8080
      - 2222:2222/tcp
      - 443:443
  dbgate:
    extends:
      file: ../../services/dbgate/docker-compose.yml
      service: dbgate
    ports:
      - 4000:3000
    depends_on:
      - postgres