services:
  mongo:
    extends:
      file: ../../services/mongo/docker-compose.yml
      service: mongo
  postgres:
    extends:
      file: ../../services/postgres/docker-compose.yml
      service: postgres
  redis:
    extends:
      file: ../../services/redis/docker-compose.yml
      service: redis
  gitlab:
    extends:
      file: ../../services/gitlab/docker-compose.yml
      service: gitlab
  rocketchat:
    extends:
      file: ../../services/rocketchat/docker-compose.yml
      service: rocketchat
    depends_on:
      - mongo
  homeassistant:
    extends:
      file: ../../services/homeassistant/docker-compose.yml
      service: homeassistant
  filestash:
    extends:
      file: ../../services/filestash/docker-compose.yml
      service: filestash
  mediamtx:
    extends:
      file: ../../services/mediamtx/docker-compose.yml
      service: mediamtx
  kratos-migrate:
    extends:
      file: ../../services/kratos/docker-compose.yml
      service: kratos-migrate
    depends_on:
      - postgres
  kratos:
    extends:
      file: ../../services/kratos/docker-compose.yml
      service: kratos
    depends_on:
      - postgres
      - kratos-migrate
  nginxproxymanager:
    extends:
      file: ../../services/nginxproxymanager/docker-compose.yml
      service: nginxproxymanager
