services:
  base:
    environment:
      - TZ=${HONEYPI_TZ:-'Europe/Amsterdam'}
      - DSN=postgres://root:${HONEYPI_POSTGRES_PASSWORD}@postgres:5432/kratos
      - LOG_LEVEL=${HONEYPI_LOG_LEVEL:-info}
      - HONEYPI_DOCKER_REGISTRY=${HONEYPI_DOCKER_REGISTRY:-'127.0.0.1:5000'}
      - ALLOW_EMPTY_PASSWORD=yes
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=${HONEYPI_AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE:-'/secrets/JWT_SECRET'}
      - AUTHELIA_SESSION_SECRET_FILE=${HONEYPI_AUTHELIA_SESSION_SECRET_FILE:-'/secrets/SESSION_SECRET'}
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=${HONEYPI_AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE:-'/secrets/STORAGE_PASSWORD'}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=${HONEYPI_AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE:-'/secrets/STORAGE_ENCRYPTION_KEY'}
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgres
      - AUTHENTIK_POSTGRESQL__USER=root
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${HONEYPI_POSTGRES_PASSWORD}
      - LLDAP_JWT_SECRET=${HONEYPI_LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${HONEYPI_LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=${HONEYPI_LLDAP_LDAP_BASE_DN}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MARIADB_ROOT_PASSWORD=${HONEYPI_MARIADB_PASSWORD}
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MATOMO_DATABASE_HOST=mariadb
      - MYSQL_PASSWORD=${HONEYPI_MARIADB_PASSWORD}
      - NEXTCLOUD_DATADIR=${HONEYPI_HOME}/nextcloud/data
      - PHOTOPRISM_ADMIN_USER=root
      - PHOTOPRISM_ADMIN_PASSWORD=${HONEYPI_PHOTOPRISM_PASSWORD}
      - PHOTOPRISM_AUTH_MODE=password
      - PHOTOPRISM_DETECT_NSFW=false
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_SERVER=mariadb
      - PHOTOPRISM_DATABASE_NAME=photoprism
      - PHOTOPRISM_DATABASE_USER=root
      - PHOTOPRISM_DATABASE_PASSWORD=${HONEYPI_MARIADB_PASSWORD}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${HONEYPI_POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      # - ROOT_URL=${HONEYPI_ROCKETCHAT_URL}
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - CORE_SECRET=${HONEYPI_CORE_SECRET}
      - CORE_DATABASE_URL=postgres://root:${HONEYPI_POSTGRES_PASSWORD}@postgres/zipline
      - DB_ADAPTER=postgresql
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - REDIS_HOST=redis
      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false
      - GITLAB_HOST=localhost
      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_ROOT_PASSWORD=${HONEYPI_GITLAB_PASSWORD}
    env_file:
      - ./../${HONEYPI_ENVIRONMENT}.env
