services:
  photoprism:
    image: photoprism/photoprism:${HONEYPI_APP_VERSION:-latest}
    container_name: photoprism
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    working_dir: /photoprism
    volumes:
      - ${HONEYPI_HOME}/photoprism/originals:/photoprism/originals
      - ${HONEYPI_HOME}/photoprism/storage:/photoprism/storage
      - ${HONEYPI_CONFIG}/photoprism/theme:/photoprism/storage/config/theme
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env
