services:
  photoprism:
    image: photoprism/photoprism:${HONEYPI_PHOTOPRISM_VERSION:-latest}
    container_name: photoprism
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    working_dir: /photoprism
    volumes:
      - ${HONEYPI_DATA}/photoprism/originals:/photoprism/originals
      - ${HONEYPI_DATA}/photoprism/storage:/photoprism/storage
    env_file:
      - ./service.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.photoprism.rule=Host(`${HONEYPI_PHOTOPRISM_HOST}`)
      - traefik.http.routers.photoprism.entrypoints=websecure
      - traefik.http.routers.photoprism.tls.certresolver=resolver
      - traefik.http.routers.photoprism.service=photoprism
      - traefik.http.services.photoprism.loadbalancer.server.port=2342