services:
  photoprism:
    image: photoprism/photoprism:${HONEYPI_PHOTOPRISM_VERSION:-latest}
    container_name: photoprism
    restart: unless-stopped
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    working_dir: /photoprism
    volumes:
      - ${HONEYPI_DATA}/photoprism/originals:/photoprism/originals
      - ${HONEYPI_DATA}/photoprism/storage:/photoprism/storage
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/photoprism/service.env
