services:
  wireguard:
    extends:
      file: ../../services/wireguard/docker-compose.yml
      service: wireguard
    restart: unless-stopped
    ports:
      - 5000:5000
      - 51820:51820/udp
  wireguard-ui:
    extends:
      file: ../../services/wireguard/docker-compose.yml
      service: wireguard-ui
    depends_on:
      - wireguard
    network_mode: service:wireguard