services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    tty: true
    stdin_open: true
    volumes:
      - ${HONEYPI_HOME}/openldap/ldap:/data/var/lib/ldap
      - ${HONEYPI_HOME}/openldap/slapd.d:/etc/ldap/slapd.d
      - ${HONEYPI_HOME}/openldap/certs:/container/service/slapd/assets/certs
    ports:
      - 389:389
      - 636:636
    extends:
      file: ../../commons/compose.yml
      service: base