services:
  lldap:
    image: lldap/lldap:latest
    ports:
      - "17170:17170"
    volumes:
      - ${HONEYPI_HOME}/lldap/data:/data
    extends:
      file: ../../commons/compose.yml
      service: base