services:
  gitlab-ce-arm64v8:
    restart: unless-stopped
    container_name: gitlab-ce
    privileged: true
    deploy:
      resources:
        limits:
          memory: 8G
    ports:
      - "8080:80"
      - "8443:443"
      - "8822:22"
    shm_size: "256m"
    volumes:
      - ${HONEYPI_HOME}/gitlab/config:/etc/gitlab'
      - ${HONEYPI_HOME}/gitlab/logs:/var/log/gitlab'
      - ${HONEYPI_HOME}/gitlab/data:/var/opt/gitlab'
    hostname: hive.honeymachine.io
    environment:
      - GITLAB_ROOT_PASSWORD=${HONEYPI_GITLAB_ROOT_PASSWORD}
      - GITLAB_OMNIBUS_CONFIG=" registry['enable'] = false;
        GITLAB_OMNIBUS[your_other_configs] = `options`; "\
    image: yrzr/gitlab-ce-arm64v8:latest‚
