services:
  gitea:
    container_name: gitea
    image: gitea/gitea:${HONEYPI_APP_VERSION:-latest}
    restart: unless-stopped
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env
    volumes:
      - ${HONEYPI_HOME}/gitea/data:/data
      - ${HONEYPI_CONFIG}/gitea/theme/public:/data/gitea/public
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    