services:
  traefik:
    image: traefik:${HONEYPI_APP_VERSION:-latest}
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.ssh.address=:2222"
      - "--certificatesresolvers.resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.resolver.acme.email=${HONEYPI_LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    volumes:
      - ${HONEYPI_DATA}/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock