services:
  elasticsearch:
    image: arm64v8/elasticsearch:7.17.4
    restart: unless-stopped
    container_name: elasticsearch
    volumes:
      - ${HONEYPI_HOME}/elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
          soft: -1
          hard: -1
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
      - bootstrap.memory_lock=true
      - node.name=es01
      - xpack.security.enabled=false
      - cluster.name=es
      - discovery.type=single-node
      