services:
  gitlab:
    image: yrzr/gitlab-ce-arm64v8:latest
    restart: unless-stopped
    container_name: gitlab
    deploy:
      resources:
        limits:
          memory: 8G
    shm_size: 256m
    volumes:
      - ${HONEYPI_HOME}/gitlab/config:/etc/gitlab'
      - ${HONEYPI_HOME}/gitlab/logs:/var/log/gitlab'
      - ${HONEYPI_HOME}/gitlab/data:/var/opt/gitlab'
    extends:
      file: ../../commons/compose.yml
      service: base
