services:
  mastodon:
    image: ghcr.io/${HONEYPI_MASTODON_GHCR_USER:-mastodon}/mastodon:${HONEYPI_MASTODON_VERSION:-latest}
    restart: unless-stopped
    container_name: mastodon
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ${HONEYPI_DATA}/mastodon/public/system:/mastodon/public/system
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/mastodon/service.env
    depends_on:
      - mastodon-init
  mastodon-init:
    image: ghcr.io/${HONEYPI_MASTODON_GHCR_USER:-mastodon}/mastodon:${HONEYPI_MASTODON_VERSION:-latest}
    restart: unless-stopped
    container_name: mastodon-init
    command: rake db:migrate
    volumes:
      - ${HONEYPI_DATA}/mastodon/public/system:/mastodon/public/system
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/mastodon/service.env
  mastodon-streaming:
    image: ghcr.io/${HONEYPI_MASTODON_GHCR_USER:-mastodon}/mastodon-streaming:${HONEYPI_MASTODON_VERSION:-latest}
    restart: unless-stopped
    container_name: mastodon-streaming
    command: node ./streaming/index.js
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/mastodon/service.env
  mastodon-sidekiq:
    image: ghcr.io/${HONEYPI_MASTODON_GHCR_USER:-mastodon}/mastodon:${HONEYPI_MASTODON_VERSION:-latest}
    restart: unless-stopped
    container_name: mastodon-sidekiq
    command: bundle exec sidekiq
    volumes:
      - ${HONEYPI_DATA}/mastodon/public/system:/mastodon/public/system
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/mastodon/service.env
