services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ${HONEYPI_HOME}/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${HONEYPI_POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    extends:
      file: ../../commons/compose.yml
      service: base
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
    extends:
      file: ../../commons/compose.yml
      service: base