services:
  rocketchat:
    image: ${HONEYPI_DOCKER_REGISTRY}/rocketchat
    container_name: rocketchat
    restart: unless-stopped
    build: .
    extends:
      file: ../../commons/compose.yml
      service: base
