services:
  rocketchat:
    image: rocketchat:latest
    container_name: rocketchat
    restart: unless-stopped
    build: .
    extends:
      file: ../../commons/compose.yml
      service: base
  rocketchat-mongo-init:
    image: arm64v8/mongo:4.4.1
    container_name: rocketchat-mongo-init
    restart: unless-stopped
    entrypoint: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''mongo:27017'' } ]})"'
    extends:
      file: ../../commons/compose.yml
      service: base