services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/nodered/data:/data
    extends:
      file: ../../commons/compose.yml
      service: base
