services:
  filestash:
    container_name: filestash
    image: machines/filestash:${HONEYPI_FILESTASH_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ${HONEYPI_DATA}/filestash/state:/app/data/state/
