services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:${HONEYPI_APP_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/homeassistant/config:/config
      - ${HONEYPI_CONFIG}/homeassistant/config/custom_components:/config/custom_components
      - ${HONEYPI_CONFIG}/homeassistant/config/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env    