services:
  mosquitto:
    image: eclipse-mosquitto:${HONEYPI_MOSQUITTO_VERSION:-latest}
    restart: unless-stopped
    container_name: mosquitto
    volumes:
      - ${HONEYPI_DATA}/mosquitto/data:/mosquitto
    command: "mosquitto -c /mosquitto-no-auth.conf"
