services:
  staticwebserver:
    image: joseluisq/static-web-server:${HONEYPI_STATICWEBSERVER_VERSION:-latest}
    container_name: staticwebserver
    restart: unless-stopped
    volumes:
      - ${HONEYPI_DATA}/staticwebserver/hosts:/srv/hosts
      - ${HONEYPI_DATA}/staticwebserver/config.toml:/etc/config.toml