services:
  redis:
    image: 'redis/redis:latest'
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - ${HONEYPI_HOME}/redis/data:/data
    extends:
      file: ../../commons/compose.yml
      service: base