services:
  redis:
    image: 'redis:${HONEYPI_APP_VERSION:-latest}'
    container_name: redis
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/redis/data:/data
    extends:
      file: ../../commons/compose.yml
      service: base
    
