services:
  rpiplay:
    image: rpiplay:${HONEYPI_APP_VERSION:-latest}
    container_name: rpiplay
    restart: unless-stopped
    build: .
    extends:
      file: ../../commons/compose.yml
      service: base