#!/bin/bash

OPTIONS="-n $AIRPIPLAY_NAME -a $AIRPIPLAY_AUDIO_OUT -b $AIRPIPLAY_BACKGROUND -r $AIRPIPLAY_ROTATION -f $AIRPIPLAY_FLIP"

[[ $AIRPIPLAY_LATENCY_MODE == 1 ]] && OPTIONS="$OPTIONS -l"

rpiplay $OPTIONS