#!/bin/bash

OPTIONS="-n $AIRPIPLAY_NAME -a $AIRPIPLAY_AUDIO_OUT -b $AIRPIPLAY_BACKGROUND -r $AIRPIPLAY_ROTATION -f $AIRPIPLAY_FLIP"

if [[ $AIRPIPLAY_LATENCY_MODE = 1 ]]; then
    OPTIONS="$OPTIONS -l"
fi

./rpiplay $OPTIONS