- name: Splashscreen
  hosts: all
  vars:
    image_url: https://www.pixelstalk.net/wp-content/uploads/images2/Fireplace-Wallpapers.jpg
    image_dest: /opt/splash.jpg
  tasks:
    - name: Update and upgrade
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg:
          - fbi
        state: present
        update_cache: true
        install_recommends: false
    - name: Download image
      become: true
      ansible.builtin.get_url:
        url: "{{ image_url }}"
        dest: "{{ image_dest }}"
        mode: "0600"
    - name: Service
      become: true
      ansible.builtin.copy:
        dest: /lib/systemd/system/splashscreen.service
        content: |
          [Unit]
          Description=Splashscreen
          DefaultDependencies=no
          After=local-fs.target

          [Service]
          ExecStart=/bin/bash /home/pole/scripts/splashscreen.sh
          StandardInput=tty
          StandardOutput=tty

          [Install]
          WantedBy=sysinit.target
        mode: "0755"
    - name: Enable Service
      become: true
      ansible.builtin.systemd:
        name: splashscreen
        state: started
    - name: Reboot
      become: true
      ansible.builtin.reboot:
