services:
  authentik:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    command: server
    volumes:
      - ${HONEYPI_HOME}/authentik/media:/media
      - ${HONEYPI_HOME}/authentik/templates:/templates
    extends:
      file: ../../commons/compose.yml
      service: base
  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HONEYPI_HOME}/authentik/media:/media
      - ${HONEYPI_HOME}/authentik/certs:/certs
      - ${HONEYPI_HOME}/authentik/templates:/templates
    extends:
      file: ../../commons/compose.yml
      service: base
