services:
  authentik:
    image: ghcr.io/goauthentik/server:${HONEYPI_APP_VERSION:-latest}
    restart: unless-stopped
    container_name: authentik
    command: server
    volumes:
      - ${HONEYPI_HOME}/authentik/media:/media
      - ${HONEYPI_HOME}/authentik/templates:/templates
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env
  authentik-worker:
    image: ghcr.io/goauthentik/server:${HONEYPI_APP_VERSION:-latest}
    restart: unless-stopped
    container_name: authentik-worker
    command: worker
    volumes:
      - ${HONEYPI_HOME}/authentik/media:/media
      - ${HONEYPI_HOME}/authentik/certs:/certs
      - ${HONEYPI_HOME}/authentik/templates:/templates
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env