services:
  zipline:
    image: ghcr.io/diced/zipline:latest
    container_name: zipline
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/zipline/uploads:/zipline/uploads'
      - ${HONEYPI_HOME}/zipline/public:/zipline/public'
    extends:
      file: ../../commons/compose.yml
      service: base
