services:
  zipline:
    image: diced/zipline:latest
    container_name: zipline
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=I love it
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://${HONEYPI_POSTGRES_USER}:${HONEYPI_POSTGRES_PASSWORD}@postgres/zipline
      - CORE_LOGGER=true
    volumes:
      - ${HONEYPI_HOME}/zipline/uploads:/zipline/uploads'
      - ${HONEYPI_HOME}/zipline/public:/zipline/public'
    extends:
      file: ../../commons/compose.yml
      service: base