services:
  sonic:
    image: valeriansaliou/sonic:${HONEYPI_SONIC_VERSION:-latest}
    container_name: sonic
    expose:
      - 1491
    volumes:
      - ${HONEYPI_CONFIG}/sonic/sonic.cfg:/etc/sonic.cfg
      - ${HONEYPI_DATA}/sonic/data:/var/lib/sonic/store
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/sonic/service.env
