services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: mediamtx
    restart: unless-stopped
    # devices:
    # - /dev/video0:/dev/video0
    volumes:
      - ${HONEYPI_HOME}/mediamtx/config/mediamtx.yml:/mediamtx.yml
      - ${HONEYPI_HOME}/mediamtx/config/server.crt:/server.crt
      - ${HONEYPI_HOME}/mediamtx/config/server.key:/server.key
    extends:
      file: ../../commons/compose.yml
      service: base
