services:
  mariadb:
    image: mariadb:${HONEYPI_MARIADB_VERSION:-latest}
    container_name: mariadb
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --init-file /data/application/init.sql --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - ${HONEYPI_DATA}/mariadb/data:/var/lib/mysql
      - ${HONEYPI_CONFIG}/mariadb/init.sql:/data/application/init.sql
    env_file:
      - ${HONEYPI_HOME:-/home/pi/honeypi}/services/mariadb/service.env
