services:
  kratos:
    image: oryd/kratos:latest
    container_name: kratos
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ${HONEYPI_HOME}/kratos/config:/etc/config/kratos
      - ${HONEYPI_KRATOS_CONFIG}:/etc/config/kratos
    extends:
      file: ../../commons/compose.yml
      service: base
  kratos-migrate:
    image: oryd/kratos:latest
    container_name: kratos-migrate
    restart: unless-stopped
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    volumes:
      - ${HONEYPI_HOME}/kratos/config:/etc/config/kratos
      - ${HONEYPI_KRATOS_CONFIG}:/etc/config/kratos
    extends:
      file: ../../commons/compose.yml
      service: base
