services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:${HONEYPI_APP_VERSION:-latest}
    container_name: nginxproxymanager
    restart: unless-stopped
    volumes:
      - ${HONEYPI_HOME}/nginxproxymanager/data:/data
      - ${HONEYPI_HOME}/nginxproxymanager/letsencrypt:/etc/letsencrypt
      - ./_hsts_map.conf:/app/templates/_hsts_map.conf
    extends:
      file: ../../commons/compose.yml
      service: base
    env_file:
      - ./service.env